name: 🐛 Bug Report
description: Report a bug or unexpected behavior in ExcelViewer
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below to help us fix it.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: "Example: Application crashes when opening Excel files larger than 50MB"
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this behavior?
      placeholder: |
        1. Open ExcelViewer
        2. Click 'Load File'
        3. Select a large Excel file
        4. Application crashes
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: "The file should load successfully"
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: "Application crashes with OutOfMemoryException"
    validations:
      required: true

  - type: dropdown
    id: operating-system
    attributes:
      label: Operating System
      description: Which OS are you running?
      options:
        - Windows
        - Linux
        - macOS
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: ExcelViewer Version
      description: Which version of ExcelViewer are you using?
      placeholder: "v1.0.0"
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or error messages here
      placeholder: "Error logs, screenshots, etc."
    validations:
      required: false

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have provided all required information above
          required: true
