name: Deploy GitHub Pages

# Trigger: quando si pusha su main e si modificano file in docs/website/
on:
  push:
    branches: [main]
    paths:
      - 'docs/website/**'
  # Permette deploy manuale da GitHub Actions tab
  workflow_dispatch:

# Permessi necessari per GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Evita deploy concorrenti
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history including tags

      - name: Regenerate website from latest tag
        run: |
          # Get latest tag by version number (not by commit distance)
          LATEST_TAG=$(git tag --sort=-version:refname | head -1 || echo "v0.1.0")
          VERSION="$LATEST_TAG"
          VERSION_NUMBER="${VERSION#v}"  # Remove 'v' prefix
          RELEASE_DATE="$(date +%Y-%m-%d)"

          echo "Regenerating website with version $VERSION"

          # Determine if this is a prerelease
          if [[ "$VERSION" == v0.* ]]; then
            IS_PRERELEASE="true"
            RELEASE_STATUS_TEXT="Alpha release - Windows and Linux installers available"
            ALPHA_BANNER="            <div style=\"background: #fff3cd; border: 1px solid #ffc107; border-radius: 8px; padding: 16px; margin-bottom: 24px; text-align: center;\"><strong>⚠️ Alpha Software:</strong> This is a pre-release version (${VERSION}). Features are functional but may contain bugs. <a href=\"https://github.com/ghostintheshell-192/sheet-atlas/releases\">View all releases →</a></div>"
          else
            IS_PRERELEASE="false"
            RELEASE_STATUS_TEXT="Stable release"
            ALPHA_BANNER=""
          fi

          # Export variables for envsubst
          export VERSION
          export VERSION_NUMBER
          export RELEASE_DATE
          export RELEASE_STATUS_TEXT
          export ALPHA_BANNER

          # Generate index.html and download.html from templates
          envsubst < docs/website/index.html.template > docs/website/index.html
          envsubst < docs/website/download.html.template > docs/website/download.html

          echo "✅ Website regenerated successfully"
          echo "   VERSION: $VERSION"
          echo "   VERSION_NUMBER: $VERSION_NUMBER"
          echo "   IS_PRERELEASE: $IS_PRERELEASE"

      - name: Run website validation tests
        run: |
          echo "🧪 Running website validation tests..."
          chmod +x docs/website/test-website.sh
          ./docs/website/test-website.sh

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Pubblica solo docs/website/ (non tutta la cartella docs!)
          path: 'docs/website'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
