name: Release with Changelog

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g., 1.0.0)'
        required: true
        type: string

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install git-cliff
        run: |
          curl -L https://github.com/orhun/git-cliff/releases/download/v2.0.4/git-cliff-2.0.4-x86_64-unknown-linux-gnu.tar.gz -o git-cliff.tar.gz
          tar -xzf git-cliff.tar.gz
          sudo mv git-cliff-*/git-cliff /usr/local/bin/
          chmod +x /usr/local/bin/git-cliff

      - name: Generate CHANGELOG
        run: |
          git-cliff --tag v${{ inputs.version }} --output CHANGELOG.md

      - name: Commit CHANGELOG
        run: |
          git add CHANGELOG.md
          git commit -m "chore(release): update CHANGELOG for v${{ inputs.version }}

          🤖 Generated with [Claude Code](https://claude.com/claude-code)

          Co-Authored-By: Claude <noreply@anthropic.com>"

      - name: Create and push tag
        run: |
          git tag -a "v${{ inputs.version }}" -m "Release v${{ inputs.version }}"
          git push origin develop
          git push origin "v${{ inputs.version }}"
